biblio_book:
    resource: "@BiblioBundle/Resources/config/routing/book.yml"
    prefix:   /book





biblio_recherche_Etudiant:
    path:   /rechercherEtudiant
    defaults:  { _controller: BiblioBundle:Etudiant:rechercher}

biblio_etudiant:
    path:    /Etudiant
    defaults:  { _controller: BiblioBundle:Etudiant:index }

biblio_etudiant_with_id:
    path:    /Etudiant/{id}
    defaults:  { _controller: BiblioBundle:Etudiant:Affichage }

biblio_etudiant_with_name:
    path:    /Etudiant/{name}
    defaults:  { _controller: BiblioBundle:Etudiant:voir }

list_etudiant:
    path:    /listEtudiants
    defaults:  { _controller: BiblioBundle:Etudiant:list }

modifier_etudiant:
    path: /updateEtudiant/{id}
    defaults: { _controller: BiblioBundle:Etudiant:update }

ajouter_etudiant:
    path:    /
    defaults:  { _controller: BiblioBundle:Etudiant:add }

supprimer_etudiant:
     path:  /deleteEtudiant/{id}
     defaults: { _controller: BiblioBundle:Etudiant:delete }
